"""add_bl_number_to_invoices

Revision ID: 238972958d6a
Revises: your_new_revision_id_here
Create Date: 2025-05-24 15:58:10.373673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238972958d6a'
down_revision: Union[str, None] = 'your_new_revision_id_here'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('bl_number', sa.String(length=100), nullable=True))
    op.drop_index('ix_invoices_status', table_name='invoices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.drop_column('invoices', 'bl_number')
    # ### end Alembic commands ###
