"""add_alt_text_to_item_images

Revision ID: 3e524cb4a2db
Revises: 81dba08ae28b
Create Date: 2025-05-24 20:04:49.497163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e524cb4a2db'
down_revision: Union[str, None] = '81dba08ae28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_images', sa.Column('alt_text', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_images', 'alt_text')
    # ### end Alembic commands ###
