"""add_shipping_fields_to_invoices

Revision ID: 6d6b8bccd275
Revises: 511e465585e3
Create Date: 2025-05-24 13:02:20.845573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d6b8bccd275'
down_revision: Union[str, None] = '511e465585e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('container_number', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('seal_number', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('hs_code', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'hs_code')
    op.drop_column('invoices', 'seal_number')
    op.drop_column('invoices', 'container_number')
    # ### end Alembic commands ###
