"""add_packing_list_fields_to_invoice_items_and_type

Revision ID: 908344afc5ef
Revises: 6d6b8bccd275
Create Date: 2025-05-24 13:43:10.121872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '908344afc5ef'
down_revision: Union[str, None] = '6d6b8bccd275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('net_weight_kgs', sa.Float(), nullable=True))
    op.add_column('invoice_items', sa.Column('gross_weight_kgs', sa.Float(), nullable=True))
    op.add_column('invoice_items', sa.Column('measurement_cbm', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'Packing List' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'invoice_type_enum')) THEN
                ALTER TYPE invoice_type_enum ADD VALUE 'Packing List';
            END IF;
        END$$;
    """)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_items', 'measurement_cbm')
    op.drop_column('invoice_items', 'gross_weight_kgs')
    op.drop_column('invoice_items', 'net_weight_kgs')
    # ### end Alembic commands ###
