"""add_invoice_template_and_org_link_v5

Revision ID: bf00805ec064
Revises: 3e524cb4a2db
Create Date: 2025-05-25 18:07:53.351017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf00805ec064'
down_revision: Union[str, None] = '3e524cb4a2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoicetemplates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_file_path', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('is_system_default', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_file_path')
    )
    op.create_index(op.f('ix_invoicetemplates_id'), 'invoicetemplates', ['id'], unique=False)
    op.create_index(op.f('ix_invoicetemplates_name'), 'invoicetemplates', ['name'], unique=True)
    op.add_column('organizations', sa.Column('selected_invoice_template_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'organizations', 'invoicetemplates', ['selected_invoice_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'selected_invoice_template_id')
    op.drop_index(op.f('ix_invoicetemplates_name'), table_name='invoicetemplates')
    op.drop_index(op.f('ix_invoicetemplates_id'), table_name='invoicetemplates')
    op.drop_table('invoicetemplates')
    # ### end Alembic commands ###
