"""add_discount_type

Revision ID: f6922ae0fb23
Revises: e623eb001e6e
Create Date: 2025-12-31 12:52:23.489543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6922ae0fb23'
down_revision: Union[str, None] = 'e623eb001e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum type explicitly
    discount_type_enum = sa.Enum('PERCENTAGE', 'FIXED', name='discount_type_enum')
    discount_type_enum.create(op.get_bind())
    
    op.add_column('invoices', sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED', name='discount_type_enum'), nullable=False, server_default='PERCENTAGE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'discount_type')
    
    # Drop the Enum type explicitly
    discount_type_enum = sa.Enum('PERCENTAGE', 'FIXED', name='discount_type_enum')
    discount_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
